-- Tasks History Table
-- This table stores the history of momentum plans generated for users
-- Optional: Run this in your Supabase SQL editor to enable persistence

-- Create tasks_history table
CREATE TABLE IF NOT EXISTS tasks_history (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  input_text TEXT NOT NULL,
  response_json JSONB NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP WITH TIME ZONE,
  
  -- Add indexes for common queries
  CONSTRAINT tasks_history_input_text_check CHECK (char_length(input_text) > 0)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_tasks_history_user_id ON tasks_history(user_id);
CREATE INDEX IF NOT EXISTS idx_tasks_history_created_at ON tasks_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_history_completed ON tasks_history(completed);

-- Enable Row Level Security
ALTER TABLE tasks_history ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- Users can only see their own history
CREATE POLICY "Users can view their own tasks history"
  ON tasks_history
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own history
CREATE POLICY "Users can insert their own tasks history"
  ON tasks_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can update their own history
CREATE POLICY "Users can update their own tasks history"
  ON tasks_history
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own history
CREATE POLICY "Users can delete their own tasks history"
  ON tasks_history
  FOR DELETE
  USING (auth.uid() = user_id);

-- Optional: Add a comment to the table
COMMENT ON TABLE tasks_history IS 'Stores history of momentum plans generated by users';
COMMENT ON COLUMN tasks_history.input_text IS 'The user input that triggered the momentum plan';
COMMENT ON COLUMN tasks_history.response_json IS 'The full JSON response including roast, tasks, and deep_dive_template';
COMMENT ON COLUMN tasks_history.completed IS 'Whether the user marked this plan as completed';
